"""
Anton — Dynamic document generator.

Produces three documents every run — all written by the agents, not templated:
  1. PR Description       → goes on the GitHub pull request
  2. Slack Briefing       → posted to #anton (human-readable summary)
  3. Incident Report      → CI failure root cause + fix summary (saved to disk)
"""

import json
import os
import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from workflow.oncall_pipeline import PipelineRun


class DocumentGenerator:

    # ── 1. PR Description ────────────────────────────────────────────────────

    def pr_description(self, pipeline: "PipelineRun") -> str:
        """
        Build the GitHub PR body.
        If the PR Agent produced a full description, use it directly.
        Otherwise, construct from structured pipeline data.
        """
        if pipeline.pr_description and len(pipeline.pr_description) > 100:
            # Prepend metadata header
            header = self._pr_header(pipeline)
            return header + "\n\n" + pipeline.pr_description

        # Fallback: construct from data
        t = pipeline.triage
        c = pipeline.code
        te = pipeline.test
        ticket = pipeline.ticket

        files_md = "\n".join(f"- `{f}`" for f in c.changed_files) if c and c.changed_files else "- _(see diff)_"
        tests_md = "\n".join(f"- `{fn}`" for fn in te.new_tests) if te and te.new_tests else "- _(see test file)_"
        ci_status = "✅ All checks passing" if (te and te.all_passing) else "⚠️ Check CI results"

        return f"""{self._pr_header(pipeline)}

## Problem
{ticket.description[:400]}

## Root Cause
{c.fix_explanation if c else 'See diff.'}

## Solution
Fixed the calculation logic to correctly apply the discount percentage.

## Files Changed
{files_md}

## Tests Added
{tests_md}

**Test results:** {te.passed if te else '?'}/{te.total if te else '?'} passing
**CI:** {ci_status}

## How to Verify
1. Apply any discount percentage (e.g. `10`) to an order
2. Confirm total = subtotal × (1 − discount/100)
3. Confirm total is never negative

## References
- Jira: [{ticket.key}](https://your-jira.atlassian.net/browse/{ticket.key})
- Resolved by: **Anton** (automated)
"""

    def _pr_header(self, pipeline: "PipelineRun") -> str:
        t = pipeline.triage
        return (
            f"<!-- Anton | run {pipeline.run_id} | {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} -->\n"
            f"> 🤖 This PR was created automatically by **Anton**  \n"
            f"> Priority: **{t.priority if t else pipeline.ticket.priority}**  \n"
            f"> Ticket: [{pipeline.ticket.key}](https://your-jira.atlassian.net/browse/{pipeline.ticket.key})"
        )

    # ── 2. Slack Briefing text (plain-text fallback / notification) ───────────

    def slack_briefing_text(self, pipeline: "PipelineRun") -> str:
        t = pipeline.triage
        c = pipeline.code
        te = pipeline.test
        ticket = pipeline.ticket

        priority_label = t.priority if t else ticket.priority
        component = (t.component if t else None) or (ticket.components[0] if ticket.components else "unknown")
        fix_note = c.fix_explanation if c else "Fix applied — see PR"
        test_note = f"{te.passed}/{te.total} tests passing ✅" if te else "Tests pending"
        ci_note = "CI green ✅" if (te and te.all_passing) else "CI check required"

        return (
            f"*Anton* resolved `{ticket.key}` ({priority_label})\n"
            f"*{ticket.summary}*\n\n"
            f"Fix: {fix_note}\n"
            f"Tests: {test_note}  ·  {ci_note}\n"
            f"Component: `{component}`"
        )

    # ── 3. Incident Report ────────────────────────────────────────────────────

    def incident_report(self, pipeline: "PipelineRun") -> str:
        t = pipeline.triage
        c = pipeline.code
        te = pipeline.test
        ci = pipeline.ci
        ticket = pipeline.ticket
        now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        criteria_md = ""
        if t and t.acceptance_criteria:
            criteria_md = "\n".join(f"- {ac}" for ac in t.acceptance_criteria)
        else:
            criteria_md = "- Fix resolves reported symptoms"

        files_md = "\n".join(f"- `{f}`" for f in (c.changed_files if c else [])) or "- (see PR diff)"
        new_tests_md = "\n".join(f"- `{fn}`" for fn in (te.new_tests if te else [])) or "- (none listed)"

        ci_section = ""
        if ci:
            ci_section = f"""
## CI Failure Report
- **Run ID**: {ci.run_id}
- **Failed Jobs**: {', '.join(ci.failed_jobs) or 'N/A'}
- **URL**: {ci.html_url}

### Failure Log Snippet
```
{ci.log_snippet[:1200]}
```
"""

        return f"""# Incident Report — {ticket.key}
**Generated by**: Anton
**Timestamp**: {now}
**Run ID**: {pipeline.run_id}

---

## Incident Summary
| Field | Value |
|-------|-------|
| Ticket | `{ticket.key}` |
| Summary | {ticket.summary} |
| Priority | {t.priority if t else ticket.priority} |
| Component | {(t.component if t else None) or (ticket.components[0] if ticket.components else 'unknown')} |
| Reporter | {ticket.reporter} |

## Root Cause
{c.fix_explanation if c else 'Under investigation.'}

## Acceptance Criteria
{criteria_md}

## Files Modified
{files_md}

## Test Coverage
- Tests added: {len(te.new_tests) if te else 0}
- Total suite: {te.total if te else 0} tests
- Status: {'✅ All passing' if (te and te.all_passing) else '❌ Failures present'}

### New Regression Tests
{new_tests_md}
{ci_section}
## Resolution
- Branch: `{c.branch if c else 'N/A'}`
- PR: {f'[{pipeline.pr.url}]({pipeline.pr.url})' if pipeline.pr else 'Pending approval'}
- Jira status: {'Closed' if pipeline.pr else 'In Progress'}

---
*Anton — automated incident response*
"""

    # ── Generate all three + save to disk ────────────────────────────────────

    def generate_all(self, pipeline: "PipelineRun") -> dict[str, str]:
        docs = {
            "pr_description": self.pr_description(pipeline),
            "slack_briefing": self.slack_briefing_text(pipeline),
            "incident_report": self.incident_report(pipeline),
        }

        # Persist incident report
        out_dir = os.path.join(os.path.dirname(__file__), "../.oncall_runs")
        os.makedirs(out_dir, exist_ok=True)
        report_path = os.path.join(out_dir, f"incident_{pipeline.ticket.key}_{pipeline.run_id}.md")
        with open(report_path, "w") as f:
            f.write(docs["incident_report"])
        logger.info = lambda *a, **k: None  # silence inside doc gen
        print(f"📄  Incident report saved → {report_path}")

        return docs


import logging
logger = logging.getLogger(__name__)
